<a href="https://colab.research.google.com/github/shrad1997/SVM/blob/main/SVM_forestfire.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# SVM Classification
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report


from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score

In [2]:
df=pd.read_csv("/content/forestfires.csv")

In [3]:
df.head(5)

month  day  FFMC   DMC  ...  monthnov  monthoct  monthsep  size_category
0   mar  fri  86.2  26.2  ...         0         0         0          small
1   oct  tue  90.6  35.4  ...         0         1         0          small
2   oct  sat  90.6  43.7  ...         0         1         0          small
3   mar  fri  91.7  33.3  ...         0         0         0          small
4   mar  sun  89.3  51.3  ...         0         0         0          small

[5 rows x 31 columns]

In [4]:
df.month.unique()

array(['mar', 'oct', 'aug', 'sep', 'apr', 'jun', 'jul', 'feb', 'jan',
       'dec', 'may', 'nov'], dtype=object)

In [5]:
df=df.drop(['month','day'],axis=1)

In [6]:
df.head(5)

FFMC   DMC     DC  ISI  ...  monthnov  monthoct  monthsep  size_category
0  86.2  26.2   94.3  5.1  ...         0         0         0          small
1  90.6  35.4  669.1  6.7  ...         0         1         0          small
2  90.6  43.7  686.9  6.7  ...         0         1         0          small
3  91.7  33.3   77.5  9.0  ...         0         0         0          small
4  89.3  51.3  102.2  9.6  ...         0         0         0          small

[5 rows x 29 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 29 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   FFMC           517 non-null    float64
 1   DMC            517 non-null    float64
 2   DC             517 non-null    float64
 3   ISI            517 non-null    float64
 4   temp           517 non-null    float64
 5   RH             517 non-null    int64  
 6   wind           517 non-null    float64
 7   rain           517 non-null    float64
 8   area           517 non-null    float64
 9   dayfri         517 non-null    int64  
 10  daymon         517 non-null    int64  
 11  daysat         517 non-null    int64  
 12  daysun         517 non-null    int64  
 13  daythu         517 non-null    int64  
 14  daytue         517 non-null    int64  
 15  daywed         517 non-null    int64  
 16  monthapr       517 non-null    int64  
 17  monthaug       517 non-null    int64  
 18  monthdec  

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
LB=LabelEncoder()
df["Size"]=LB.fit_transform(df["size_category"])
df

FFMC    DMC     DC   ISI  ...  monthoct  monthsep  size_category  Size
0    86.2   26.2   94.3   5.1  ...         0         0          small     1
1    90.6   35.4  669.1   6.7  ...         1         0          small     1
2    90.6   43.7  686.9   6.7  ...         1         0          small     1
3    91.7   33.3   77.5   9.0  ...         0         0          small     1
4    89.3   51.3  102.2   9.6  ...         0         0          small     1
..    ...    ...    ...   ...  ...       ...       ...            ...   ...
512  81.6   56.7  665.6   1.9  ...         0         0          large     0
513  81.6   56.7  665.6   1.9  ...         0         0          large     0
514  81.6   56.7  665.6   1.9  ...         0         0          large     0
515  94.4  146.0  614.7  11.3  ...         0         0          small     1
516  79.5    3.0  106.7   1.1  ...         0         0          small     1

[517 rows x 30 columns]

In [10]:
df=df.drop(['size_category'],axis=1)

In [11]:
df.columns

Index(['FFMC', 'DMC', 'DC', 'ISI', 'temp', 'RH', 'wind', 'rain', 'area',
       'dayfri', 'daymon', 'daysat', 'daysun', 'daythu', 'daytue', 'daywed',
       'monthapr', 'monthaug', 'monthdec', 'monthfeb', 'monthjan', 'monthjul',
       'monthjun', 'monthmar', 'monthmay', 'monthnov', 'monthoct', 'monthsep',
       'Size'],
      dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 29 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   FFMC      517 non-null    float64
 1   DMC       517 non-null    float64
 2   DC        517 non-null    float64
 3   ISI       517 non-null    float64
 4   temp      517 non-null    float64
 5   RH        517 non-null    int64  
 6   wind      517 non-null    float64
 7   rain      517 non-null    float64
 8   area      517 non-null    float64
 9   dayfri    517 non-null    int64  
 10  daymon    517 non-null    int64  
 11  daysat    517 non-null    int64  
 12  daysun    517 non-null    int64  
 13  daythu    517 non-null    int64  
 14  daytue    517 non-null    int64  
 15  daywed    517 non-null    int64  
 16  monthapr  517 non-null    int64  
 17  monthaug  517 non-null    int64  
 18  monthdec  517 non-null    int64  
 19  monthfeb  517 non-null    int64  
 20  monthjan  517 non-null    int64 

In [13]:
X=df.iloc[:,0:28]
Y=df.iloc[:,28]

In [14]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.3)

In [15]:
#Grid search CV
clf = SVC()
param_grid = [{'kernel':['rbf'],'gamma':[50,5,10,0.5],'C':[15,14,13,12,11,10,0.1,0.001] }]
gsv = GridSearchCV(clf,param_grid,cv=10)
gsv.fit(X_train,Y_train)

GridSearchCV(cv=10, estimator=SVC(),
             param_grid=[{'C': [15, 14, 13, 12, 11, 10, 0.1, 0.001],
                          'gamma': [50, 5, 10, 0.5], 'kernel': ['rbf']}])

In [16]:
gsv.best_params_ , gsv.best_score_ 

({'C': 15, 'gamma': 0.5, 'kernel': 'rbf'}, 0.7561561561561561)

In [17]:
clf = SVC(C= 15, gamma = 0.5)
clf.fit(X_train , Y_train)
y_pred = clf.predict(X_test)
acc = accuracy_score(Y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(Y_test, y_pred)

Accuracy = 69.87179487179486


array([[  2,  47],
       [  0, 107]])

In [18]:
clf = SVC(kernel= "linear") 
clf.fit(X_train , Y_train)
y_pred = clf.predict(X_test)
acc = accuracy_score(Y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(Y_test, y_pred)  

Accuracy = 97.43589743589743


array([[ 49,   0],
       [  4, 103]])

In [19]:
clf = SVC(kernel= "poly") 
clf.fit(X_train , Y_train)
y_pred = clf.predict(X_test)
acc = accuracy_score(Y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(Y_test, y_pred) 

Accuracy = 75.0


array([[ 10,  39],
       [  0, 107]])